{
 "title": "C9800-WLC-PS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Source",
    "label": "Device",
    "query": "show tag values with key = \"source\""
   },
   {
    "name": "NAME",
    "label": "Interface",
    "query": "show tag values with key = \"name\""
   },
   {
    "name": "Client",
    "query": "SHOW TAG VALUES WITH KEY = \"ms_mac_address\""
   },
   {
    "name": "APMAC",
    "query": "SELECT distinct(\"wtp_mac\") FROM \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-name-mac-map\" WHERE (\"wtp_name\" =~ /^$APName$/)"
   },
   {
    "name": "APName",
    "query": "SHOW TAG VALUES WITH KEY = \"wtp_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "WLC Status and Health Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Model",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-platform-oper:components/component/state",
       "select": [
        [
         { "params": [ "description" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    },
    {
     "title": "WLC-IP",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-interfaces-oper:interfaces/interface",
       "select": [
        [
         { "params": [ "ipv4" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    },
    {
     "title": "Serial No",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-platform-oper:components/component/state",
       "select": [
        [
         { "params": [ "serial_no" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-native:native",
       "select": [
        [
         { "params": [ "version" ], "type": "field" },
         { "params": [ "Version" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    },
    {
     "title": "HA",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-platform-software-oper:cisco-platform-software/control-processes/control-process",
       "select": [
        [
         { "params": [ "chassis_state" ], "type": "field" },
         { "params": [ "HA" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "chassis::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization",
       "select": [
        [
         { "params": [ "one_minute" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CPU" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=", "value": "WLC" }
       ]
      }
     ]
    },
    {
     "title": "INTERFACE STATUS",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name::tag" ], "type": "tag" }
       ],
       "measurement": "ietf-interfaces:interfaces-state/interface",
       "select": [
        [
         { "params": [ "oper_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Protocol Status" ], "type": "alias" }
        ],
        [
         { "params": [ "admin_status" ], "type": "field" },
         { "params": [ "Admin Status" ], "type": "alias" }
        ],
        [
         { "params": [ "speed" ], "type": "field" },
         { "params": [ " / 1000000000" ], "type": "math" },
         { "params": [ "Speed(Gb)" ], "type": "alias" }
        ],
        [
         { "params": [ "phys_address" ], "type": "field" },
         { "params": [ "MAC Address" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$NAME$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 12, "y": 7 },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic",
       "select": [
        [
         { "params": [ "total_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 1000000000" ], "type": "math" },
         { "params": [ "Total Memory" ], "type": "alias" }
        ],
        [
         { "params": [ "free_memory" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 1000000000" ], "type": "math" },
         { "params": [ "Free Memory" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Processor" }
       ]
      }
     ]
    },
    {
     "title": "CDP Neighbor",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail",
       "select": [
        [
         { "params": [ "local_intf_name" ], "type": "field" },
         { "params": [ "Local-iface" ], "type": "alias" }
        ],
        [
         { "params": [ "device_name" ], "type": "field" },
         { "params": [ "Neighbor" ], "type": "alias" }
        ],
        [
         { "params": [ "port_id" ], "type": "field" },
         { "params": [ "Neighbor-PortID" ], "type": "alias" }
        ],
        [
         { "params": [ "mgmt_address" ], "type": "field" },
         { "params": [ "Neighbor-MGMT-IP" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "AP & SSID",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total No. Of AP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-mobility-oper:mobility-oper-data/ap-peer-list",
       "select": [
        [
         { "params": [ "ap_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    },
    {
     "title": "AP $APName 5GHz Channel/AirTime Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-rrm-oper:rrm-oper-data/rrm-measurement",
       "select": [
        [
         { "params": [ "load/rx_util_percentage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RX Uti" ], "type": "alias" }
        ],
        [
         { "params": [ "load/tx_util_percentage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "TX Uti" ], "type": "alias" }
        ],
        [
         { "params": [ "load/cca_util_percentage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Total Channel Uti" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "wtp_mac::tag", "operator": "=~", "value": "/^$APMAC$/" },
        { "condition": "AND", "key": "radio_slot_id::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "AP $APName 2.4GHz Channel/AirTime Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-rrm-oper:rrm-oper-data/rrm-measurement",
       "select": [
        [
         { "params": [ "load/rx_util_percentage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RX Uti" ], "type": "alias" }
        ],
        [
         { "params": [ "load/tx_util_percentage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "TX Uti" ], "type": "alias" }
        ],
        [
         { "params": [ "load/cca_util_percentage" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Total Channel Uti" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "wtp_mac::tag", "operator": "=~", "value": "/^$APMAC$/" },
        { "condition": "AND", "key": "radio_slot_id::tag", "operator": "=", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "No. Of Client",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "wlan_profile::tag" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-mobility-oper:mobility-oper-data/wlan-client-limit",
       "select": [
        [
         { "params": [ "curr_clients_count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Total Client" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    },
    {
     "title": "No. of 5Ghz Client connect in $APName",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 13 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "wlan_id::tag" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ssid-counters",
       "select": [
        [
         { "params": [ "num_assoc_clients" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "wtp_mac::tag", "operator": "=~", "value": "/^$APMAC$/" },
        { "condition": "AND", "key": "slot_id::tag", "operator": "=", "value": "1" }
       ]
      }
     ]
    },
    {
     "title": "CAPWAP $APName Data",
     "type": "table",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 13 },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/capwap-data",
       "select": [
        [
         { "params": [ "wtp_ip" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "AP IP" ], "type": "alias" }
        ],
        [
         { "params": [ "ap_keepalive_state" ], "type": "field" },
         { "params": [ "KeepAlive" ], "type": "alias" }
        ],
        [
         { "params": [ "ap_mode_data/wtp_mode" ], "type": "field" },
         { "params": [ "Mode" ], "type": "alias" }
        ],
        [
         { "params": [ "ap_time_info/boot_time" ], "type": "field" },
         { "params": [ "Boot Time" ], "type": "alias" }
        ],
        [
         { "params": [ "ap_time_info/join_time" ], "type": "field" },
         { "params": [ "Join Time" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "device_detail/static_info/ap_models/model"
          ],
          "type": "field"
         },
         { "params": [ "AP Model" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "device_detail/static_info/board_data/wtp_serial_num"
          ],
          "type": "field"
         },
         { "params": [ "Serial No" ], "type": "alias" }
        ],
        [
         {
          "params": [
           "device_detail/wtp_version/sw_version"
          ],
          "type": "field"
         },
         { "params": [ "SW Version" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "wtp_mac::tag", "operator": "=~", "value": "/^$APMAC$/" }
       ]
      }
     ]
    },
    {
     "title": "AP $APName Channel Details",
     "type": "table",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 18 },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/radio-oper-data",
       "select": [
        [
         {
          "params": [
           "phy_ht_cfg/cfg_data/freq_string"
          ],
          "type": "field"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "phy_ht_cfg/cfg_data/curr_freq" ], "type": "field" },
         { "params": [ "Current Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "current_active_band" ], "type": "field" },
         { "params": [ "Band Type" ], "type": "alias" }
        ],
        [
         { "params": [ "phy_he_cap/data/he_enabled" ], "type": "field" },
         { "params": [ "802.1ax Enable" ], "type": "alias" }
        ],
        [
         { "params": [ "phy_ht_cfg/cfg_data/chan_width" ], "type": "field" },
         { "params": [ "Channel Width(MHz)" ], "type": "alias" }
        ],
        [
         { "params": [ "slot_id" ], "type": "field" },
         { "params": [ "Slot ID" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "wtp_mac::tag", "operator": "=~", "value": "/^$APMAC$/" }
       ]
      }
     ]
    },
    {
     "title": "AP Join Stats",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "wtp_mac::tag" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-ap-global-oper:ap-global-oper-data/ap-join-stats/ap-join-info",
       "select": [
        [
         { "params": [ "ap_name" ], "type": "field" },
         { "params": [ "AP Name" ], "type": "alias" }
        ],
        [
         { "params": [ "ap_ip_addr" ], "type": "field" },
         { "params": [ "IP Address" ], "type": "alias" }
        ],
        [
         { "params": [ "is_joined" ], "type": "field" },
         { "params": [ "Joined(True/False)" ], "type": "alias" }
        ],
        [
         { "params": [ "last_error_type" ], "type": "field" },
         { "params": [ "Error Type" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Client Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client RSSI SNR for $Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
       "select": [
        [
         { "params": [ "most_recent_rssi" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "RSSI" ], "type": "alias" }
        ],
        [
         { "params": [ "most_recent_snr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [
           10
          ],
          "type": "moving_average"
         },
         { "params": [ "SNR" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "ms_mac_address", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "bytes RX & TX for $Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
       "select": [
        [
         { "params": [ "bytes_rx" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RX" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_tx" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "TX" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "ms_mac_address", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "Data Rate for $Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Mbps" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
       "select": [
        [
         { "params": [ "speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Speed" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "ms_mac_address", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "Client $Client connects to the AP",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/common-oper-data",
       "select": [
        [
         { "params": [ "ap_name" ], "type": "field" },
         { "params": [ "Connected AP" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan_id" ], "type": "field" },
         { "params": [ "WLANID" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "client_mac::tag", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "Dot11-Details for client $Client",
     "type": "table",
     "gridPos": { "h": 4, "w": 7, "x": 6, "y": 11 },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/dot11-oper-data",
       "select": [
        [
         { "params": [ "vap_ssid" ], "type": "field" },
         { "params": [ "SSID" ], "type": "alias" }
        ],
        [
         { "params": [ "current_channel" ], "type": "field" },
         { "params": [ "Channel" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "ms_mac_address::tag", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "Client Device Details",
     "type": "table",
     "gridPos": { "h": 4, "w": 7, "x": 13, "y": 11 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/dc-info",
       "select": [
        [
         { "params": [ "device_os" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "OS-Version" ], "type": "alias" }
        ],
        [
         { "params": [ "device_type" ], "type": "field" },
         { "params": [ "Device-Type" ], "type": "alias" }
        ],
        [
         { "params": [ "device_name" ], "type": "field" },
         { "params": [ "Device-Name" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "client_mac::tag", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "Client IPv4",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/sisf-db-mac",
       "select": [
        [
         { "params": [ "ipv4_binding/ip_key/ip_addr" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "mac_addr::tag", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "Radio Type",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/dot11-oper-data",
       "select": [
        [
         { "params": [ "radio_type" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "ms_mac_address::tag", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    },
    {
     "title": "NSS",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-wireless-client-oper:client-oper-data/traffic-stats",
       "select": [
        [
         { "params": [ "spatial_stream" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source::tag", "operator": "=~", "value": "/^$Source$/" },
        { "condition": "AND", "key": "ms_mac_address::tag", "operator": "=~", "value": "/^$Client$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}